#ddev-generated
## Command provided by https://github.com/ddev/ddev-drupal-contrib
hooks:
  post-start:
    - exec-host: |
        if [[ -f vendor/autoload.php ]]; then
          ddev symlink-project
        else
          exit 0
        fi
